### ISSUE TITLE
Can we increase the default speed? 

### ISSUE THREAD

**Issue by mkoller** [quangdaon/jquery-ticker#1]
in `jquery-ticker/src/js/defaults.js` you set the speed 

```// Number: Speed of ticker in Pixels/Second.
	speed: 60, 
```

But can we increase it to `speed: 70`as the default?

**Comment by quangdaon** [comment]
Hm... I went with 60 since it's an even 60 pixels/second or 1 px/frame. But I suppose if more people prefer that it starts faster, we can bump it up a bit. Not sure if there's enough of a benefit at the moment.

**Comment by mkoller** [comment]
What does @joshplate think?

**Comment by JoshPlate** [comment]
How about we start at 88??

![88 mph](https://78.media.tumblr.com/773fffaf35a6220646a48ca7493379fa/tumblr_n3fglaTjS41r5s4n9o8_500.gif)

**Comment by quangdaon** [comment]
I don't think there's enough of a benefit for changing the default setting at the moment. The speed can be set upon initiation for specific use cases requiring the ticker to be faster.
